export const mockTasks =
{
  tags: ['My tasks', 'escuela', 'programming', 'casa'],
  tasks: [
    {
      "name": "Uno",
      "tag": "escuela",
      "id": 1,
      "description": "In congue. Etiam justo. Etiam pretium iaculis justo.",
      "date": "06/22/2022",
      "type": "regular",
      "blocks": null,
      "repeat": false,
      "repeatOn": null,
    },
    {
      "name": "Dos",
      "tag": "escuela",
      "id": 2,
      "description": "In congue. Etiam justo. Etiam pretium iaculis justo.",
      "date": "06/21/2022",
      "type": "block",
      "blocks": 2, 
      "repeat": false,
      "repeatOn": null,
    },
    {
      "name": "Tres",
      "tag": "escuela",
      "id": 3,
      "description": "In congue. Etiam justo. Etiam pretium iaculis justo.",
      "date": "06/23/2022",
      "type": "block",
      "blocks": 3,
      "repeat": false,
      "repeatOn": null,
    },
    {
      "name": "Cuatro",
      "tag": "escuela",
      "id": 4,
      "description": "In congue. Etiam justo. Etiam pretium iaculis justo.",
      "date": "06/21/2022",
      "type": "regular",
      "blocks": null,
      "repeat": false,
      "repeatOn": null,
    },
    {
      "name": "Cinco",
      "tag": "escuela",
      "id": 5,
      "description": "In congue. Etiam justo. Etiam pretium iaculis justo.",
      "date": "06/24/2022",
      "type": "regular",
      "blocks": null,
      "repeat": false,
      "repeatOn": null,
    },
    {
      "name": "Seis",
      "tag": "escuela",
      "id": 6,
      "description": "In congue. Etiam justo. Etiam pretium iaculis justo.",
      "date": "06/25/2022",
      "type": "regular",
      "blocks": null,
      "repeat": false,
      "repeatOn": null,
    },
    {
      "name": "Siete",
      "tag": "escuela",
      "id": 7,
      "description": "In congue. Etiam justo. Etiam pretium iaculis justo.",
      "date": "24/07/2022",
      "type": "regular",
      "blocks": null,
      "repeat": false,
      "repeatOn": "day",
    },
    {
      "name": "Ocho",
      "tag": "casa",
      "id": 8,
      "description": "In congue. Etiam justo. Etiam pretium iaculis justo.",
      "date": null,
      "type": "regular",
      "blocks": null,
      "repeat": true,
      "repeatOn": [0],
    },
    {
      "name": "Nueve",
      "tag": "programming",
      "id": 9,
      "description": "In congue. Etiam justo. Etiam pretium iaculis justo.",
      "date": null,
      "type": "regular",
      "blocks": null,
      "repeat": true,
      "repeatOn": [0, 3, 6],
    },
    {
      "name": "Diez",
      "tag": "programming",
      "id": 10,
      "description": "In congue. Etiam justo. Etiam pretium iaculis justo.",
      "date": null,
      "type": "regular",
      "blocks": null,
      "repeat": true,
      "repeatOn": "day",
    },

  ],
  history: [{
    "complete_date": "06/06/2022",
    "pomodoros": 1500,
    "tag": "My tasks"
  }, {
    "complete_date": "06/16/2022",
    "pomodoros": 7500,
    "tag": "Programming"
  }, {
    "complete_date": "06/06/2022",
    "pomodoros": 750,
    "tag": "casa"
  }, {
    "complete_date": "06/05/2022",
    "pomodoros": 3000,
    "tag": "escuela"
  }, {
    "complete_date": "04/10/2022",
    "pomodoros": 4500,
    "tag": "programming"
  }],
}


